// Règles du pseudo joueur — source unique, partagée par le client (retour
// immédiat dans le formulaire) et par la route serveur (autorité réelle).
//
// Le pseudo est PUBLIC : il apparaît dans les enchères, les collections et les
// pages joueur. Il mérite donc d'être stable, lisible et non usurpable.
//
// Répartition des responsabilités, volontairement asymétrique :
//   • ce module            = la règle métier, testée ;
//   • la route API         = l'autorité (revalide tout, ne fait jamais confiance
//                            au client) ;
//   • l'index unique en DB = le juge de paix sur les collisions (deux requêtes
//                            simultanées passent la vérification puis se
//                            télescopent : seule la contrainte tranche) ;
//   • le trigger SQL       = un simple filet, qui assainit sans valider —
//                            il ne doit JAMAIS faire échouer une inscription.

export const USERNAME_MIN = 3;
export const USERNAME_MAX = 20;

/** Lettres, chiffres, tiret et souligné. Pas d'espace ni de ponctuation : le
 *  pseudo sert d'identité affichée, pas de phrase. Pas d'accents non plus —
 *  « Élan » et « Elan » se ressembleraient trop pour deux comptes distincts. */
const USERNAME_RE = /^[A-Za-z0-9_-]+$/;

/** Pseudos interdits : ils laisseraient croire à un compte officiel. La
 *  comparaison se fait en minuscules, donc « AdMiN » est couvert. */
const RESERVED = new Set([
  "admin", "administrateur", "administrator", "moderateur", "moderator", "mod",
  "staff", "support", "officiel", "official", "system", "systeme", "root",
  "armies", "armiesandmagic", "armiesmagic", "am",
  "null", "undefined", "anonymous", "anonyme",
]);

export type UsernameError =
  | "too_short"
  | "too_long"
  | "invalid_chars"
  | "reserved";

/** Forme canonique : espaces de bord retirés. La casse est CONSERVÉE — le
 *  joueur garde le pseudo tel qu'il l'a écrit — mais l'unicité, elle, est
 *  insensible à la casse (index sur lower(username)). Deux comptes ne peuvent
 *  donc pas s'appeler « Grognak » et « grognak ». */
export function normalizeUsername(raw: string): string {
  return raw.trim();
}

/** `null` si le pseudo est valide, sinon le motif du refus. Ne dit RIEN de la
 *  disponibilité : seule la base peut trancher (cf. l'index unique). */
export function validateUsername(raw: string): UsernameError | null {
  const value = normalizeUsername(raw);
  if (value.length < USERNAME_MIN) return "too_short";
  if (value.length > USERNAME_MAX) return "too_long";
  if (!USERNAME_RE.test(value)) return "invalid_chars";
  if (RESERVED.has(value.toLowerCase())) return "reserved";
  return null;
}

/** Un pseudo produit automatiquement (repli du trigger `Player_xxxxxxxx`, ou
 *  l'ancien `Player_<base36>` que le formulaire générait) n'a été choisi par
 *  personne : l'écran d'accueil doit inviter à en prendre un vrai.
 *
 *  Sert de FILET pour les comptes créés avant l'ajout de `username_confirmed`.
 *  Le drapeau reste la source de vérité — ce test n'est qu'un repli, car un
 *  joueur a parfaitement le droit de choisir « Player_1234 » délibérément. */
export function looksAutoGenerated(username: string): boolean {
  return /^Player_[0-9a-f]{8}$/i.test(username) || /^Player_[0-9a-z]{6,12}$/.test(username);
}
