// Règles du pseudo. Seule partie du flux d'inscription réellement testable
// hors bout-en-bout : tout le reste est de l'I/O Supabase.
import { describe, expect, it } from "vitest";
import {
  USERNAME_MAX,
  USERNAME_MIN,
  looksAutoGenerated,
  normalizeUsername,
  validateUsername,
} from "./username";

describe("normalizeUsername", () => {
  it("retire les espaces de bord", () => {
    expect(normalizeUsername("  Grognak \n")).toBe("Grognak");
  });

  it("CONSERVE la casse : le joueur garde le pseudo tel qu'il l'a écrit", () => {
    expect(normalizeUsername("GroGnak")).toBe("GroGnak");
  });
});

describe("validateUsername", () => {
  it("accepte lettres, chiffres, tiret et souligné", () => {
    for (const ok of ["Grognak", "elfe_noir", "Nain-42", "abc", "a".repeat(USERNAME_MAX)]) {
      expect(validateUsername(ok)).toBeNull();
    }
  });

  it("refuse trop court / trop long, bornes comprises", () => {
    expect(validateUsername("a".repeat(USERNAME_MIN - 1))).toBe("too_short");
    expect(validateUsername("a".repeat(USERNAME_MIN))).toBeNull();
    expect(validateUsername("a".repeat(USERNAME_MAX))).toBeNull();
    expect(validateUsername("a".repeat(USERNAME_MAX + 1))).toBe("too_long");
  });

  it("mesure la longueur APRÈS trim : les espaces ne font pas le compte", () => {
    expect(validateUsername("  ab  ")).toBe("too_short");
  });

  it("refuse espaces, accents et ponctuation", () => {
    for (const ko of ["deux mots", "Élan", "grognak!", "a.b", "emoji🐉"]) {
      expect(validateUsername(ko)).toBe("invalid_chars");
    }
  });

  it("refuse les pseudos réservés, quelle que soit la casse", () => {
    for (const ko of ["admin", "AdMiN", "Support", "MODERATEUR", "official"]) {
      expect(validateUsername(ko)).toBe("reserved");
    }
  });

  it("un mot réservé n'est interdit qu'exactement : « admin » ≠ « adminou »", () => {
    expect(validateUsername("adminou")).toBeNull();
    expect(validateUsername("xadmin")).toBeNull();
  });

  it("refuse le vide et le tout-espaces", () => {
    expect(validateUsername("")).toBe("too_short");
    expect(validateUsername("   ")).toBe("too_short");
  });
});

describe("looksAutoGenerated", () => {
  it("reconnaît le repli du trigger (8 hexa de l'uuid) et l'ancien repli client", () => {
    expect(looksAutoGenerated("Player_3f2a9c1d")).toBe(true);
    expect(looksAutoGenerated("Player_lx8f2k")).toBe(true);
  });

  it("laisse tranquille un pseudo choisi", () => {
    for (const chosen of ["Grognak", "PlayerOne", "Player", "joueur_42"]) {
      expect(looksAutoGenerated(chosen)).toBe(false);
    }
  });
});
