import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import UsernameForm from "@/components/auth/UsernameForm";
import { looksAutoGenerated } from "@/lib/auth/username";

export const metadata = { title: "Choisis ton nom | Armies & Magic" };

// Écran de choix du pseudo, montré une seule fois : après une inscription OAuth
// (aucun pseudo n'a été saisi) ou quand le trigger a dû en suffixer un pour
// cause de collision.
//
// L'aiguillage vers cette page se fait en DEUX points seulement — ici même et
// dans src/app/page.tsx — et surtout PAS dans src/proxy.ts : celui-ci s'exécute
// à chaque navigation, et y ajouter une lecture de `profiles` coûterait une
// requête en base par page vue.
export default async function OnboardingPseudoPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: profile } = await supabase
    .from("profiles")
    .select("username, username_confirmed")
    .eq("id", user.id)
    .single();

  // Déjà validé : on ne redemande pas. Sans cette garde, un joueur qui revient
  // sur l'URL se verrait proposer de rechoisir son nom sans raison.
  if (profile?.username_confirmed) redirect("/");

  // Un pseudo auto-généré ne mérite pas d'être pré-rempli : le champ part vide
  // pour inviter à un vrai choix. Un pseudo saisi puis suffixé, en revanche,
  // est proposé tel quel — le joueur n'a qu'à l'ajuster.
  const current = profile?.username ?? "";
  const initialValue = looksAutoGenerated(current) ? "" : current;

  return <UsernameForm initialValue={initialValue} />;
}
